### ISSUE TITLE
Specific feed always has 1 unread article

### ISSUE THREAD

**Issue by gabrielmaldi** [relikd/baRSS#6]
Thanks for this awesome app, I love it!

**EDIT**

I think that the problem arises do to another feed: http://www.padreydecano.com/cms/feed/
If I delete this feed and re add it, it works initially:

<img width="367" alt="Screen Shot 2020-08-31 at 11 12 20" src="https://user-images.githubusercontent.com/3728897/91729598-2efc1a80-eb7b-11ea-8e35-92216bd662d7.png">

<img width="350" alt="Screen Shot 2020-08-31 at 11 12 22" src="https://user-images.githubusercontent.com/3728897/91729602-315e7480-eb7b-11ea-8c69-962a33681b2f.png">

But then all articles for the feed are removed and the unread badge assigned to another feed:

<img width="464" alt="Screen Shot 2020-08-31 at 11 13 29" src="https://user-images.githubusercontent.com/3728897/91729779-74204c80-eb7b-11ea-80c5-a442501a5d49.png">

-----

I found that http://feeds.feedburner.com/GitBlame always indicates (1) unread article both in the menu item (but not in the list of articles itself):

<img width="409" alt="Screen Shot 2020-08-31 at 11 08 07" src="https://user-images.githubusercontent.com/3728897/91729088-6918ec80-eb7a-11ea-9dd6-90da4c665ba4.png">

<img width="572" alt="Screen Shot 2020-08-31 at 11 08 13" src="https://user-images.githubusercontent.com/3728897/91729095-6ae2b000-eb7a-11ea-9d42-62fa09a6d2fb.png">

If I click on "Mark all read" inside the feed, nothing happens. If I click on the top level (all fees) "Mark all read" menu item, the article does get marked as read and the indicator disappears but only for a while, then it returns.

Thanks again!

**Comment by relikd** [comment]
I am not sure if these are really related though. I did accidentially reproduce the other behaviour (empty menu) and was able to narrow it down. This doesn't explain the "(1)" though. Anyway, maybe it was indeed a side effect of the bug. Can you open the Setting > About, and click on "Fix Cache". If that fixes the issue for you, you should be good. Also make sure to update to `1.1.1` which fixes the issue (hopefully).

And many thanks for the credits much appreciated. I haven't actively advertised my app yet (too busy lately). That means, you found it by some lucky accident, hurray 😄

**Comment by gabrielmaldi** [comment]
Thanks for your quick response! I reinstalled macOS and since I didn't like the RSS app I was using before very much, I searched for another one and found yours. So far it's been great! Simple, fast, unobtrusive and love the grouping and UI customization options ❤️.

Just updated to `1.1.1` and clicked "Fix Cache", will wait a couple of days and report back. Thanks!

**Comment by gabrielmaldi** [comment]
It's worked flawlessly for a couple of days now so I'm closing this issue 😊. Thanks again!
