### ISSUE TITLE
Show unread items in separate list

### ISSUE THREAD

**Issue by maliMirkec** [relikd/baRSS#8]
It would be great to have all the unread items in a separate list (see image below).

![image](https://user-images.githubusercontent.com/2345786/193293772-d9cdb023-6039-49ef-867f-85cf589786a6.png)

**Comment by relikd** [comment]
Can you elaborate your use-case? What do you want to do with that list? (I am not arguing against it, just want to understand the purpose).

Do you want a list of all unread items regardless which feed they are from? In that case you will loose the context information. E.g. you just see the title "Wing Lift" and you will have no clue that this is from the xkcd feed.

Do you want such a list for each group or just an overall unread list?

**Comment by maliMirkec** [comment]
The purpose is to find unread items more quickly.

For example, I have imported the whole web dev feeds with 1000 feeds, and it is very hard to find all updates.

I would prefer not to lose the context, so maybe there could be a new list that contains only unread feeds. ¯\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/2345786/193395677-4c47a530-629f-460a-8aa4-4380c7465961.png)

**Comment by relikd** [comment]
Ahh, I see. So it would be not helpful to display all unread entries in a single list because that would mean in your case a list of 465 entries. How about an option to hide feeds that have no unread entries? So if you would hover over the "web dev" group it would only display "Use Tables!" and no other feed of the shown (...plus the other feeds that have unread items). Or do you really want a separate list with only unread articles?

**Comment by maliMirkec** [comment]
The first option would be perfect.

**Comment by relikd** [comment]
Lets have a look at [release v1.2.0](https://github.com/relikd/baRSS/releases/tag/v1.2.0).

This release will probably show the unidentified developer warning again (updated my developer certificate a while ago). If a dialog says you can't open the app, just right click and select Open.

**Comment by maliMirkec** [comment]
I've just installed v1.2.0. This is what I see:
![image](https://user-images.githubusercontent.com/2345786/193427119-ff84126a-4eb2-4b40-ae52-683e1f29f924.png)

**Comment by relikd** [comment]
you need to activate the option in settings

**Comment by maliMirkec** [comment]
Works!
Thanks for the quick response.

\m/
